<?php

namespace App\Enums;

enum FedExServiceType: string
{
    case PRIORITY_OVERNIGHT = 'PRIORITY_OVERNIGHT';
    case FEDEX_GROUND = 'FEDEX_GROUND';
    case GROUND_HOME_DELIVERY = 'GROUND_HOME_DELIVERY';
    case FEDEX_2_DAY = 'FEDEX_2_DAY';
    case INTERNATIONAL_PRIORITY = 'INTERNATIONAL_PRIORITY';
    case INTERNATIONAL_ECONOMY = 'INTERNATIONAL_ECONOMY';
    case STANDARD_OVERNIGHT = 'STANDARD_OVERNIGHT';
    case FIRST_OVERNIGHT = 'FIRST_OVERNIGHT';
    case FEDEX_EXPRESS_SAVER = 'FEDEX_EXPRESS_SAVER';
}
